CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
#CPPFLAGS += -DMUTILADEBUG
#CPPFLAGS += -DDEBUG
#CPPFLAGS += -DMEMDEBUG
ARDUINO_LIBS = Mutila Adafruit_NeoPixel EEPROM MemoryFree
BOARD_TAG = nano
BOARD_SUB = atmega328

include ../arduino.mk

