CPPFLAGS += -Wno-unused-variable -Wno-deprecated-declarations -Wno-cpp -Wno-write-strings
CPPFLAGS += -DMUTILADEBUG
CPPFLAGS += -DDEBUG
ARDUINO_LIBS = Mutila Adafruit_NeoPixel EEPROM
BOARD_TAG = nano
BOARD_SUB = atmega328

include ../arduino.mk

